name: donggong
description: "A Modern Hitomi Reader"
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ^3.10.7

dependencies:
  cached_network_image: ^3.4.1
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  http: ^1.6.0
  intl: ^0.20.2
  metadata_god: ^1.1.0
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^4.0.0
  sqflite: ^2.4.2
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0+1

flutter:
  uses-material-design: true
