name: donggong
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  cached_network_image: ^3.4.1
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  http: ^1.6.0
  intl: ^0.20.2
  metadata_god: ^1.1.0
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
